stow -vv ctags
stow -vv compton
stow -vv gem
stow -vv git
stow -vv gtk2
stow -vv gtk3
stow -vv less
stow -vv neovim
stow -vv readline
stow -vv redshift
stow -vv reek
stow -vv rofi
stow -vv rspec
stow -vv tmux
stow -vv vim
stow -vv xmodmap
stow -vv yaourt
stow -vv zsh
