[planner]
ignore_ingredients = [
  "active dry yeast",
  "agave syrup",
  "all-purpose flour",
  "baking powder",
  "baking soda",
  "bay leaf",
  "bbq rub",
  "better than bouillon - seasoned vegetable base",
  "black beans",
  "black pepper",
  "black peppercorn",
  "bread flour",
  "bread machine yeast",
  "bread",
  "brown sugar",
  "butter",
  "cajun seasoning",
  "canned diced tomatoes",
  "canola oil",
  "cayenne pepper",
  "chicken broth",
  "chicken stock",
  "chili powder",
  "chocolate chips",
  "cinnamon",
  "coconut milk",
  "confectioner's sugar",
  "coriander seed",
  "coriander",
  "crushed red pepper",
  "cumin",
  "dark brown sugar",
  "diced pickled jalapenos",
  "dijon mustard",
  "dill weed",
  "dried basil",
  "dried oregano",
  "dried parsley",
  "dried rosemary",
  "dried thyme",
  "dry rub",
  "egg yolk",
  "egg",
  "eggs",
  "extra virgin olive oil",
  "extra-virgin olive oil",
  "fennel seeds",
  "fine sea salt",
  "flour",
  "freshly ground black pepper",
  "garam masala",
  "garlic powder",
  "garlic salt",
  "grapeseed oil",
  "grated garlic",
  "grated ginger",
  "ground allspice",
  "ground cardamon",
  "ground cinnamon",
  "ground cloves",
  "ground coriander",
  "ground cumin",
  "ground ginger",
  "ground nutmeg",
  "ground red pepper",
  "ground turmeric",
  "honey",
  "hot sauce",
  "ice cube",
  "ice",
  "instant yeast",
  "ketchup",
  "kosher salt",
  "kosher salt",
  "large pinch salt",
  "lemon juice",
  "margarine",
  "marjoram",
  "mayo",
  "milk",
  "minced garlic",
  "minced ginger",
  "olive oil",
  "onion powder",
  "paprika",
  "peppercorns",
  "prepared mustard",
  "red pepper flakes",
  "rice",
  "salt and pepper",
  "salt",
  "sausage",
  "sea salt",
  "seasoned salt",
  "smoked paprika",
  "sriracha sauce",
  "sugar",
  "table salt",
  "taco seasoning mix",
  "thyme",
  "tomato paste",
  "tomato sauce",
  "turmeric",
  "unseasoned meat tenderizer",
  "unsweetened cocoa powder",
  "vanilla extract",
  "vegan butter",
  "vegetable oil",
  "vegetable oil",
  "vinegar",
  "warm water",
  "water",
  "white pepper",
  "whole milk",
  "worcestershire sauce",
  "yellow corn meal",
  ]
