# vim:foldmethod=marker:foldlevel=0
$mainMod = SUPER

# {{{ applications
bind = $mainMod, T, exec, rofi -show window -font "Hack Nerd Font 36"
bind = $mainMod, D, exec, rofi -show drun -font "Hack Nerd Font 36"
bind = $mainMod, Return, exec, alacritty
bind = $mainMod, X, exec, scrot -s -e 'xclip -selection clipboard -t image/png -i $f'
bind = $mainMod, Z, exec, scrot -s - | xclip -selection clipboard -t image/png
bind = $mainMod, Q, killactive
# }}}
# {{{ touchpad
bind = $mainMod CTRL, Q, exec, hyprctl keyword device:at-translated-set-2-keyboard:enabled false
bind = $mainMod CTRL, W, exec, hyprctl keyword device:at-translated-set-2-keyboard:enabled true
# }}}
# {{{ volume
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% && pactl set-sink-mute @DEFAULT_SINK@ 0
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5% && pactl set-sink-mute @DEFAULT_SINK@ 0
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
# }}}
# {{{ screen brightness
bind = , XF86MonBrightnessUp, exec, light -A 20
bind = , XF86MonBrightnessDown, exec, light -U 20
# }}}
# {{{ workspaces
# workspace names: 1/CODE, 2/BROWSE, 3/CHAT, 4-10
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
bind = $mainMod CTRL, 9, movetoworkspace, 9
bind = $mainMod CTRL, 0, movetoworkspace, 10
# }}}
# {{{ focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
# }}}
# {{{ hyprland control
bind = $mainMod CTRL, C, exec, hyprctl reload

# system submap
bind = $mainMod CTRL, E, submap, system
submap = system
# (m)onitors, (g)ammastep, (l)ock, (e)xit, (s)uspend, (r)eboot, (Shift+s)hutdown
bind = , L, exec, hyprlock
bind = , L, submap, reset
bind = , S, exec, systemctl suspend
bind = , S, submap, reset
bind = , E, exec, hyprctl dispatch exit
bind = , E, submap, reset
bind = , R, exec, systemctl reboot
bind = , R, submap, reset
bind = SHIFT, S, exec, systemctl poweroff
bind = SHIFT, S, submap, reset
bind = , M, exec, ~/.config/i3/monitors.sh
bind = , M, submap, reset
bind = , G, exec, ~/.config/i3/gammastep_toggle.sh
bind = , G, submap, reset
bind = , Return, submap, reset
bind = , Escape, submap, reset
submap = reset
# }}}
# {{{ resize submap
bind = $mainMod, R, submap, resize
submap = resize
binde = , J, resizeactive, -10 0
binde = , L, resizeactive, 10 0
binde = , K, resizeactive, 0 10
binde = , H, resizeactive, 0 -10
bind = , Return, submap, reset
bind = , Escape, submap, reset
submap = reset
# }}}
# {{{ window manipulation submap
bind = $mainMod, E, submap, window_manipulation
submap = window_manipulation
bind = , A, focuswindow, parent
bind = , J, movewindow, d
bind = , K, movewindow, u
bind = , H, movewindow, l
bind = , L, movewindow, r
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = , O, togglefloating
bind = , F, fullscreen, 0
bind = , P, togglesplit
bind = , Return, submap, reset
bind = , Escape, submap, reset
submap = reset
# }}}
