require('init/plugins')
require('init/settings')
require('init/abbr')
require('init/maps')
require('init/statusline')
require('init/commands')

require('init/plugin_config/auto-pairs')
require('init/plugin_config/fzf')
require('init/plugin_config/tig')
require('init/plugin_config/undotree')
require('init/plugin_config/vcs-jump')
require('init/plugin_config/vim-argwrap')
require('init/plugin_config/vim-rspec')
require('init/plugin_config/vim-ruby')
require('init/plugin_config/vim-tmux-navigator')
require('init/plugin_config/lsp')
