(defun kdt-setup-linum ()
  (require 'linum-relative)
  (setq linum-relative-current-symbol "")
  (add-hook 'ruby-mode-hook 'linum-mode)
  (add-hook 'rhtml-mode-hook 'linum-mode)
  (add-hook 'emacs-lisp-mode-hook 'linum-mode)
  (add-hook 'js-mode-hook 'linum-mode))
